staging-settings:
  evms:
    - chain-selector: "16015286601757825753"
      rpc-url: "https://ethereum-sepolia-rpc.publicnode.com"
production-settings:
  evms:
    - chain-selector: "16015286601757825753"
      rpc-url: "https://ethereum-sepolia-rpc.publicnode.com"
