# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "workflow-xdc-staging"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.staging.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "workflow-xdc"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.production.json"
    secrets-path: "../secrets.yaml"
